name: Validate SQL Queries

on:
  push:
    branches: [ "**" ]

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    env:
      API_URL: "https://pg-advisor.itatmisis.ru/api/validate-query"
      DB_NAME: "demo"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install requests
        sudo apt-get install -y jq
        
    - name: Validate SQL files
      run: |
        FAILED_VALIDATION=false
        HAS_QUERY_RULES=false
        
        find . -name '*.sql' | while read -r sqlfile; do
          echo "Validating $sqlfile"
          
          sql_content=$(cat "$sqlfile" | jq -Rs . | sed 's/^"//;s/"$//')
          json_payload="{\"query\": \"$sql_content\", \"dbname\": \"$DB_NAME\"}"
          
          response=$(curl -s -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -d "$json_payload")
          
          overall_valid=$(echo "$response" | jq -r '.overall_valid')
          query_rules=$(echo "$response" | jq -r '.query_rules | length')
          
          if [ "$overall_valid" = "false" ]; then
            echo "❌ Validation failed for $sqlfile"
            echo "$response" | jq .
            FAILED_VALIDATION=true
          elif [ "$query_rules" -gt 0 ]; then
            echo "::warning file=$sqlfile::Query has $query_rules optimization suggestions"
            echo "🟡 Validation passed with query rules for $sqlfile"
            echo "Query rules details:"
            echo "$response" | jq '.query_rules'
            HAS_QUERY_RULES=true
          else
            echo "✅ Validation passed for $sqlfile"
          fi
        done
        
        if [ "$FAILED_VALIDATION" = "true" ]; then
          echo "::error::Some queries failed validation"
          exit 1
        elif [ "$HAS_QUERY_RULES" = "true" ]; then
          echo "::error::Some queries have optimization suggestions"
          exit 1
        fi
